-- 聊天邀请表
CREATE TABLE IF NOT EXISTS chat_invitation (
    id          INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    inviter_id  INT UNSIGNED NOT NULL COMMENT '邀请者ID',
    invitee_id  INT UNSIGNED NOT NULL COMMENT '受邀者ID',
    chatroom_id INT UNSIGNED NOT NULL COMMENT '聊天室ID',
    FOREIGN KEY (inviter_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (invitee_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;